version: "3.7"
services:
  api_service:
    image: "user-management:latest"
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgresql_db
    links:
      - postgresql_db:postgresql_db
  postgresql_db:
    image: "postgres:15-alpine3.17"
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: java_to_dev_app_db
      POSTGRES_USER: java_to_dev
      POSTGRES_PASSWORD: KAMSciao12@ai